[build]
  command = "npm i elm && npm i elm-live && elm-live src/Main.elm -u -- --output=src/elm.js && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200